name: LmvAC
version: '1.0.73'
main: dev.lmv.lmvac.LmvAC
api-version: '1.16'
description: "by LmvDev / Support: dsc.gg/lmvdev (AntiCheat) [RECODE.v2]"
softdepend: [Geyser-Spigot,ProtocolLib]
authors:
  - billzxzs
  - KlovyEuV2
commands:
  lmvac:
    usage: §4Использование §8- §7/<command> help
  lmvlua:
    aliases: [lmvaclua,luachecks]
